sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
- composer
- "$HOME/.composer/cache"
php:
- '5.6'
- '7.0'
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=nightly WP_MULTISITE=0
services:
- mysql
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
script:
- composer test
before_deploy:
- echo 'Making deploy packages...'
- rm -rfv .git
- rm -rfv bin
- rm -rfv tests
- rm -rfv .gitignore
- rm -rfv .travis.yml
- rm -rfv vendor
- rm -rfv composer.lock
- rm -rfv phpunit.xml.dist
- zip -r rest-pattern.zip ./
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GWJRd9L86mDqGzTBf1TT6mTDCSID8D6ggUKPFhmKXmAzuaW038vTmRqpc0zLQ7HEbXpKqJvBrEgZmoG8QNC+X+CHcNwmhDXCPNy62RKep1ibtPGMIwDR/OSfUIjLegLvl29DwkkClNhtUYEn6U+jf1P9R0eIJre0qGvGkS7MFTw329S+1b2ODkMiyRZzsa8k8+6eI/Pvr2x+i6/34XW8Aw4XtWkg+KiGNAFH420h4IFy7iZu6UIjThvL+ehYixpcUeZczfZd5b3D8yNCDF9XVU4hnVV4P1hS3aIioi3Cskjnr8UL5CRB7MGW/bdUzkOOw0m7QfJ0pf1Mlx4vYROxkhB7UG4q1CA3sHqFLReAoh2G9wYe+xDQ+kHtYpa1ZR26BkrRhJQLg8aJxbTXjBSW50ogreTgBEH+GNU1VKjch/FtRn4p9JgRPSU0XFbCfOftq83bjHAXyMpgi9n9m54rsWlX7epw1WYdEtz2xufyUy3Ghf3qhXIQZvKkaq6jhCu9fMdEFW94BG2Nfw8wWuiuGs6lm5Brw/VE49aJGj2s2n/YqigmWhJgWhqob0+WvAG3GZ71y9jPzbs1dqm8N3leJHGwrYA/KxjlzWEr9w7v8JlfzoUgXMc7XhNVIbRCQB6e7cVC0on/7SeokJiMG7MIaxXqkLNhv1kLPGaCNs+zW2M=
  file: rest-pattern.zip
  on:
    repo: hametuha/rest-pattern
    tags: true
    php: '7.0'
